# Generated by Django 3.0.3 on 2020-03-19 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_link', models.TextField()),
                ('source_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime(2020, 3, 19, 14, 33, 55, 690837, tzinfo=utc))),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='newsScrapper.Source')),
            ],
        ),
    ]
