# Generated by Django 3.0.3 on 2020-03-19 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsScrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 14, 34, 11, 946742, tzinfo=utc)),
        ),
    ]
