# Generated by Django 3.0.3 on 2020-03-19 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsScrapper', '0002_auto_20200319_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
