# Generated by Django 2.2.5 on 2020-02-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsScrapper', '0002_remove_headlines_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headlines',
            old_name='url',
            new_name='link',
        ),
    ]
