# Generated by Django 3.0.3 on 2020-03-21 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsScrapper', '0003_auto_20200319_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
