# Generated by Django 3.0.3 on 2020-03-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsScrapper', '0005_auto_20200321_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='published_date',
        ),
    ]
