# Generated by Django 3.0.3 on 2020-06-09 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsScrapper', '0006_remove_headline_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='source',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
